### ISSUE TITLE
No support for per-executor maven repository

### ISSUE THREAD

**Issue by aidanhs** [jenkinsci/maven-repo-cleaner-plugin#3]
We use per-executor strategy to reduce disk space. Unfortunately this leaves us will massive maven repositories since there's no way of cleaning them (that I'm aware of).

**Comment by pjaffe** [comment]
I just configured this plugin to run on a schedule, and I was keeping my fingers crossed that it would handle per-executor repos, since we use those as well.

Based on this open issue, I'm guessing the plugin doesn't handle those.  Any chance there are people still contributing to this project who might implement it?

**Comment by mingfan** [comment]
keep eye on this
